# -*- coding: utf-8 -*-
"""Lhama_fine_tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Epaa_h011gi9Yr8xnPqq4x934F1WdHPd

<a href="https://colab.research.google.com/github/Marcos-Med/IC/blob/main/FineTuningBERTimbau.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Realizando Fine Tuning no modelo BERTimbau
<p> Foi realizado um ajuste fino no modelo léxico BERTimbau, utilizando o corpus FakeBR. O objetivo do fine tuning é criar um modelo que preveja se uma notícia é verdadeira ou não.</p>

### Clonando o corpura que se encontra no repositório do GitHub
"""

# git clone https://github.com/Marcos-Med/IC.git

"""### Instalando as bibliotecas"""

# pip install transformers torch

# pip install datasets

# importando libs
import torch
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
import pandas as pd
import os
from datasets import Dataset
from sklearn.model_selection import KFold

"""### Importando os dados do Corpora FakeBR"""

def load_corpus_fakeBR():
    base_path = "fakebr/size_normalized_texts"

    fake_news = []
    true_news = []
    for root, dirs, files in os.walk(base_path + "/fake"):
        for file in files:
            if file.endswith('.txt'):
                with open(os.path.join(root, file), 'r') as f:
                    text = f.read()
                    fake_news.append([text, 0])

    for root, dirs, files in os.walk(base_path + "/true"):
        for file in files:
            if file.endswith('.txt'):
                with open(os.path.join(root, file), 'r') as f:
                    text = f.read()
                    true_news.append([text, 1])


    all_news = fake_news + true_news
    return pd.DataFrame(all_news, columns=['text', 'label'])

#Carregando o corpus fakeBR
fake_br = load_corpus_fakeBR()

fake_br.head()

# Separar os dados textuais e a labels
text = fake_br['text']
labels = fake_br['label']

"""### Importando o modelo BERTimbau da NeuralMind"""

model_name = "neuralmind/bert-base-portuguese-cased"
tokenizer = BertTokenizer.from_pretrained(model_name)

#Função para tokenizar os dados para o modelo BERTimbau
def tokenize(data):
  return tokenizer(data['text'], padding='max_length', truncation=True, max_length=512)

#Tokeniza os dados do Corpora FakeBR
dataset = Dataset.from_pandas(fake_br)
tokenized_dataset = dataset.map(tokenize, batched=True)

# Transformar o dataset em tensor do Pytorch
tokenized_dataset = tokenized_dataset.remove_columns(['text'])
tokenized_dataset.set_format("torch")

"""### Treinamento utilizando Validação Cruzada
**K** = 5 folds
"""

# 5 folds para validação cruzada
Kf = KFold(n_splits=5, shuffle=True, random_state=42)

results = []

os.environ["WANDB_DISABLED"] = "true"

for train_index, test_index, in Kf.split(tokenized_dataset):
    train_dataset = tokenized_dataset.select(train_index.tolist())
    test_dataset = tokenized_dataset.select(test_index.tolist())

    model = BertForSequenceClassification.from_pretrained(model_name, num_labels=2) #Classificação binária

    # Paramêtros para realizar Fine Tuning no BERTimbau
    training_args = TrainingArguments(
        output_dir="./results",
        eval_strategy="epoch",
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        num_train_epochs=3,
        weight_decay=0.01,
        logging_dir="./logs",
        save_strategy="epoch"
        )
    #Objeto de treino
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=test_dataset
    )

    #Treina o modelo
    trainer.train()

    #Avaliação do modelo BERTimbau
    metrics = trainer.evaluate()
    results.append(metrics)

model.save_pretrained("save_model")
tokenizer.save_pretrained("save_tokenizer")

"""### Avaliação do Modelo Após Fine-Tuning"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification

saved_tokenizer = "save_tokenizer"

tokenizer = AutoTokenizer.from_pretrained(saved_tokenizer)

#Carrega o modelo treinado
saved_model = "save_model"
model = AutoModelForSequenceClassification.from_pretrained(saved_model)

def load_corpus_fakeBR():
    base_path = "fakebr/size_normalized_texts"

    fake_news = []
    true_news = []
    for root, dirs, files in os.walk(base_path + "/fake"):
        for file in files:
            if file.endswith('.txt'):
                with open(os.path.join(root, file), 'r') as f:
                    text = f.read()
                    fake_news.append([text, 0])

    for root, dirs, files in os.walk(base_path + "/true"):
        for file in files:
            if file.endswith('.txt'):
                with open(os.path.join(root, file), 'r') as f:
                    text = f.read()
                    true_news.append([text, 1])


    all_news = fake_news + true_news
    return pd.DataFrame(all_news, columns=['text', 'label'])

# !git clone https://github.com/Marcos-Med/IC.git

import os
import pandas as pd
fake_br = load_corpus_fakeBR()

encodings = tokenizer(fake_br['text'].tolist(), truncation=True, padding="max_length", max_length=512)

from torch.utils.data import Dataset

class CustomDataset(Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        # Criação do item com as encodings
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}

        # Verifique se as labels não são None antes de adicionar ao item
        if self.labels is not None:
            item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)  # Certifique-se de que os labels são do tipo correto

        return item

    def __len__(self):
        return len(self.encodings["input_ids"])

labels = fake_br['label'].tolist()
labels = torch.tensor(labels, dtype=torch.long)

eval_dataset = CustomDataset(encodings, labels)

from transformers import Trainer, TrainingArguments

# Configuração dos argumentos de avaliação
training_args = TrainingArguments(
    output_dir="./results",
    per_device_eval_batch_size=8,  # Ajuste conforme a sua capacidade de memória
    no_cuda=True,  # Caso não tenha GPU disponível
)

# Criar o objeto Trainer
trainer = Trainer(
    model=model,  # O modelo treinado
    args=training_args,
    eval_dataset=eval_dataset  # Passando o dataset de avaliação
)

# Avaliar o modelo
metrics = trainer.evaluate()

# Imprimir ou salvar as métricas
print(metrics)

# Salvar as métricas em um arquivo JSON
import json
with open("metrics_results.json", "w") as f:
    json.dump(metrics, f, indent=4)
