# -*- coding: utf-8 -*-
"""ACH2197-ExemploPLN_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NQmrY07hnQv34UCBzySC3kTllQzmnC9h
"""



"""# Pipeline de experimentos PLN

Este notebook é dedicado a criar uma estrutura de pipeline que será utilizada para exemplificar PLN na disciplina ACH2197 - Análise de Redes Sociais

## 1. Estruturação dos dados

Primeiro, vamos importar o conjunto de dados. O conjunto de dados foi extraído de factck.br.

Moreno, João; Bressan, Graça. FACTCK.BR: A New Dataset to Study Fake News. In: ANAIS DO SIMPÓSIO BRASILEIRO DE SISTEMAS MULTIMÍDIA E WEB (WEBMEDIA), 25. , 2019, Rio de Janeiro. Porto Alegre: Sociedade Brasileira de Computação, 2019. p. 525-527.
"""

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

import pandas as pd
dados = pd.read_csv('https://raw.githubusercontent.com/digiampietri/basesDeDados/main/factck_br_VF.csv', sep=',', decimal = ',', encoding = 'ISO-8859-1')
dados

"""Agora, vamos definir as variáveis de interesse (ou seja, a variável texto e a categoria que será prevista). Além disso, vamos utilizar o *Counter* para avaliar se há desbalanceamento entre as classes."""

from collections import Counter

X = dados['claimReviewed']
y = dados['alternativeName']

Counter(y)

"""Por fim, vamos dividir o conjunto de dados em duas partições: a de treinamento e a de teste. Isso será feito utilizando o comando *stratify* para que sejam mantidas as mesmas proporções entre as classes no conjunto de treinamento e de teste."""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123, stratify=y)

Counter(y_test)

"""## 2. Criação de modelos

Agora, vamos criar os modelos que serão testados na última etapa. Primeiro, vamos importar as bibliotecas que utilizaremos:
"""

# Pipelines
from sklearn.pipeline import Pipeline

# Engenharia de Características (features)
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import MinMaxScaler

# Modelos
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn import svm

# Métricas
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score, confusion_matrix

"""Agora, vamos utilizar o Grid Search CV para criar os modelos com os melhores hiperparâmetros.

OBS.: O pipeline para o teste dos modelos possui uma etapa de pré-processamento, que também pode impactar (muito) no desempenho de cada modelo e, consequentemente, na escolha dos hiperparâmetros. Isso é uma falha no pipeline que eu ainda preciso pensar em como melhorar.

OBS2.: O código fica comentado porque, no caso de um "Run all" acidental, ele demora um bocado para rodar.
"""

from unicodedata import normalize

minhaStopList = [normalize('NFKD', n).encode('ASCII', 'ignore').decode('ASCII') for n in stopwords.words('portuguese')]
minhaStopList.append('ii')

baseline = DummyClassifier(strategy='most_frequent', random_state = 100, constant = None)
reglog = LogisticRegression(class_weight='balanced', max_iter=2000, solver='liblinear', penalty='l2', C=1.3225)
mlp = MLPClassifier(activation='relu', max_iter=2000)
NB = MultinomialNB()

SVM = svm.SVC(kernel='poly', C = 1, gamma=1)

"""## 3. Comparação dos modelos

Agora, vamos criar um pipeline de pipelines para comparar diferentes combinações de modelos e pré-processamentos diferentes. Abaixo, crio uma lista com todas as combinações que quero testar.

OBS.: É importante dar um nome bom para cada uma das etapas; isso vai ajudar a identificar o modelo em questão na fase de comparações.
"""

# modelos1: conjunto de modelos que não usam seleção de atributos
modelos1 = [Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('dummy', baseline)]),
           Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('NB', NB)]),
           Pipeline(steps=[('tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,)),
                              ('NB', NB)]),
           Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('relog', reglog)]),
           Pipeline(steps=[('tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,)),
                              ('relog', reglog)]),
           Pipeline(steps=[('bigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('NB', NB)]),
           Pipeline(steps=[('trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('NB', NB)]),
           Pipeline(steps=[('uni-bi-trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('NB', NB)]),
           Pipeline(steps=[('bigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('NB', NB)]),
           Pipeline(steps=[('trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('NB', NB)]),
           Pipeline(steps=[('uni-bi-trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('NB', NB)]),
           Pipeline(steps=[('bigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('relog', reglog)]),
           Pipeline(steps=[('trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('relog', reglog)]),
           Pipeline(steps=[('uni-bi-trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('relog', reglog)]),
           Pipeline(steps=[('bigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('relog', reglog)]),
           Pipeline(steps=[('trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('relog', reglog)]),
           Pipeline(steps=[('uni-bi-trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('relog', reglog)]),
           Pipeline(steps=[('bigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('mlp', mlp)]),
           Pipeline(steps=[('trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('mlp', mlp)]),
           Pipeline(steps=[('uni-bi-trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('mlp', mlp)]),
           Pipeline(steps=[('bigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('mlp', mlp)]),
           Pipeline(steps=[('trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('mlp', mlp)]),
           Pipeline(steps=[('uni-bi-trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('mlp', mlp)]),
           Pipeline(steps=[('bigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('SVM', SVM)]),
           Pipeline(steps=[('trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('SVM', SVM)]),
           Pipeline(steps=[('uni-bi-trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('SVM', SVM)]),
           Pipeline(steps=[('bigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('SVM', SVM)]),
           Pipeline(steps=[('trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('SVM', SVM)]),
           Pipeline(steps=[('uni-bi-trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('SVM', SVM)]),
           ]

# modelos2: conjunto de modelos que usam seleção de atributos com a função SelectKBest
atributos  = 300
modelos2 = [Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('dummy', baseline)]),
           Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,)),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('NB', NB)]),
           Pipeline(steps=[('tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,)),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('NB', NB)]),
           Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,)),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('reglog', reglog)]),
           Pipeline(steps=[('tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,)),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('reglog', reglog)]),
           Pipeline(steps=[('bigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('NB', NB)]),
           Pipeline(steps=[('trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('NB', NB)]),
           Pipeline(steps=[('uni-bi-trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('NB', NB)]),
           Pipeline(steps=[('bigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('NB', NB)]),
           Pipeline(steps=[('trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('NB', NB)]),
           Pipeline(steps=[('uni-bi-trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('NB', NB)]),
           Pipeline(steps=[('bigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('relog', reglog)]),
           Pipeline(steps=[('trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('relog', reglog)]),
           Pipeline(steps=[('uni-bi-trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('relog', reglog)]),
           Pipeline(steps=[('bigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('relog', reglog)]),
           Pipeline(steps=[('trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('relog', reglog)]),
           Pipeline(steps=[('uni-bi-trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('relog', reglog)]),
           Pipeline(steps=[('bigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('uni-bi-trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('bigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('uni-bi-trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('bigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('uni-bi-trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('bigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('uni-bi-trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('KBest', SelectKBest(chi2, k=atributos)),
                              ('SVM', SVM)]),
           ]

# modelos3: conjunto de modelos que utilizam redução de dimensionalidade usando Análise de Componentes Principais (PCA)
modelos3 = [Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('pca', TruncatedSVD(atributos)),
                              ('dummy', baseline)]),
           Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('pca', TruncatedSVD(atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,)),
                              ('pca', TruncatedSVD(atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('pca', TruncatedSVD(atributos)), ('Normalizing',MinMaxScaler()),
                              ('NB', NB)]),
           Pipeline(steps=[('tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,)),
                              ('pca', TruncatedSVD(atributos)), ('Normalizing',MinMaxScaler()),
                              ('NB', NB)]),
           Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('pca', TruncatedSVD(atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,)),
                              ('pca', TruncatedSVD(atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('bag-of-words', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList)),
                              ('pca', TruncatedSVD(atributos)),
                              ('reglog', reglog)]),
           Pipeline(steps=[('tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,)),
                              ('pca', TruncatedSVD(atributos)),
                              ('reglog', reglog)]),
           Pipeline(steps=[('bigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('pca', TruncatedSVD(atributos)), ('Normalizing',MinMaxScaler()),
                              ('NB', NB)]),
           Pipeline(steps=[('trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('pca', TruncatedSVD(atributos)), ('Normalizing',MinMaxScaler()),
                              ('NB', NB)]),
           Pipeline(steps=[('uni-bi-trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('pca', TruncatedSVD(atributos)), ('Normalizing',MinMaxScaler()),
                              ('NB', NB)]),
           Pipeline(steps=[('bigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('pca', TruncatedSVD(atributos)), ('Normalizing',MinMaxScaler()),
                              ('NB', NB)]),
           Pipeline(steps=[('trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('pca', TruncatedSVD(atributos)), ('Normalizing',MinMaxScaler()),
                              ('NB', NB)]),
           Pipeline(steps=[('uni-bi-trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('pca', TruncatedSVD(atributos)), ('Normalizing',MinMaxScaler()),
                              ('NB', NB)]),
           Pipeline(steps=[('bigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('pca', TruncatedSVD(atributos)),
                              ('relog', reglog)]),
           Pipeline(steps=[('trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('pca', TruncatedSVD(atributos)),
                              ('relog', reglog)]),
           Pipeline(steps=[('uni-bi-trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('pca', TruncatedSVD(atributos)),
                              ('relog', reglog)]),
           Pipeline(steps=[('bigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('pca', TruncatedSVD(atributos)),
                              ('relog', reglog)]),
           Pipeline(steps=[('trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('pca', TruncatedSVD(atributos)),
                              ('relog', reglog)]),
           Pipeline(steps=[('uni-bi-trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('pca', TruncatedSVD(atributos)),
                              ('relog', reglog)]),
           Pipeline(steps=[('bigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('pca', TruncatedSVD(atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('pca', TruncatedSVD(atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('uni-bi-trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('pca', TruncatedSVD(atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('bigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('pca', TruncatedSVD(atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('pca', TruncatedSVD(atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('uni-bi-trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('pca', TruncatedSVD(atributos)),
                              ('mlp', mlp)]),
           Pipeline(steps=[('bigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('pca', TruncatedSVD(atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('pca', TruncatedSVD(atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('uni-bi-trigram', CountVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('pca', TruncatedSVD(atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('bigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(2,2))),
                              ('pca', TruncatedSVD(atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(3,3))),
                              ('pca', TruncatedSVD(atributos)),
                              ('SVM', SVM)]),
           Pipeline(steps=[('uni-bi-trigram tf-idf', TfidfVectorizer(strip_accents='ascii', lowercase=True, stop_words=minhaStopList,ngram_range=(1,3))),
                              ('pca', TruncatedSVD(atributos)),
                              ('SVM', SVM)]),
           ]

"""# Cada bloco a seguir avalia um conjunto de modelos
Os modelos são avaliados considerando validação cruzada utilizando o conjunto de treinamento.

# Modelos que não utilizam nenhuma abordagem de seleção de atributos/redução de dimensionalidade.
"""

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

kf = StratifiedKFold(n_splits=3, random_state = 123, shuffle = True)

testados = modelos1

for m in testados:
  print([i for i,j in m.steps], '\tf1_macro\t', round(cross_val_score(m, x_train, y_train, cv=kf, scoring='f1_macro').mean(), 3))
  print([i for i,j in m.steps], '\taccuracy\t', round(cross_val_score(m, x_train, y_train, cv=kf, scoring='accuracy').mean(), 3))
  print([i for i,j in m.steps], '\troc_auc\t', round(cross_val_score(m, x_train, y_train, cv=kf, scoring='roc_auc').mean(), 3))

"""# Modelos que utilizam seleção de atributos (utilizando a função SelectKBest)."""

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

kf = StratifiedKFold(n_splits=3, random_state = 123, shuffle = True)

testados = modelos2

for m in testados:
  print([i for i,j in m.steps], '\tf1_macro\t', round(cross_val_score(m, x_train, y_train, cv=kf, scoring='f1_macro').mean(), 3))
  print([i for i,j in m.steps], '\taccuracy\t', round(cross_val_score(m, x_train, y_train, cv=kf, scoring='accuracy').mean(), 3))
  print([i for i,j in m.steps], '\troc_auc\t', round(cross_val_score(m, x_train, y_train, cv=kf, scoring='roc_auc').mean(), 3))

"""# Modelos que utilizam redução de dimensionalidade usando Análise de Componentes Principais (PCA)"""

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

kf = StratifiedKFold(n_splits=3, random_state = 123, shuffle = True)

testados = modelos3

for m in testados:
  print([i for i,j in m.steps], '\tf1_macro\t', round(cross_val_score(m, x_train, y_train, cv=kf, scoring='f1_macro').mean(), 3))
  print([i for i,j in m.steps], '\taccuracy\t', round(cross_val_score(m, x_train, y_train, cv=kf, scoring='accuracy').mean(), 3))
  print([i for i,j in m.steps], '\troc_auc\t', round(cross_val_score(m, x_train, y_train, cv=kf, scoring='roc_auc').mean(), 3))

"""Os diferentes modelos foram avaliados com validação cruzada (usando apenas o conjunto de treinamento). O melhor "deve" ser o selecionado e seu desempenho deverá ser avaliado com o conjunto de teste.

## 4. Teste do modelo escolhido

Testa-se o modelo escolhido (teoricamente o que obteve o melhor desempenho). O modelo é treinado com todo o conjunto de treinamento e testado com o conjunto de teste.
"""

from sklearn import metrics # Métricas para avaliação da classificação

modelos1[2].fit(x_train, y_train)

preds = modelos1[2].predict(x_test) ### escolha um modelo para verificar seu desemepnho no conjunto de teste
report=metrics.classification_report(y_test,preds)
print(report)

"""Pipeline de experimentos adaptado de notebook desenvolvido pela ex-aluna Laís Carraro."""