# -*- coding: utf-8 -*-
"""ACH2197-ExemploPLN_Representacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWmwQa1f5OD3EWwGEgBQsSCrzSy0drD0
"""



"""# Representação de Texto para ser utilizado por classificadores

Notebook exemplificando o uso de BOW (Bag-of-Words) com contagem de palavras ou TF-IDF e n-gramas de caracteres.

Serão removidas as stopwords, o texto será convertido para letras minúsculas sem acentos e caracteres especiais.

# Bibliotecas Utilizadas

Utilizaremos as stopwords do nltk e pdandas para gerenciamento dos dados.

O conjunto de dados de entrada terá apenas o nome de duas disciplinas de SI.
"""

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

import pandas as pd
dados = pd.read_csv('http://www.each.usp.br/digiampietri/ACH2197/dados/PLN_dados_duas_disciplinas.csv', sep='\t', decimal = '.', encoding = 'UTF-8')
nomes = dados['Nome']
dados

"""## Modelos de Representação

Agora, vamos criar os modelos que serão testados na última etapa. Primeiro, vamos importar as bibliotecas que utilizaremos:
"""

# Extração das características dos textos (TFIDF e contagem de n-gramas)
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

"""Inicialmente os textos serão representados como unigramas de palavras e o peso corresponderá a contagem de cada unigrama em cada texto."""

vectorizer = CountVectorizer()
processado = vectorizer.fit_transform(nomes)
print(nomes)
print(processado.toarray())
vectorizer.get_feature_names_out()

vectorizer2 = TfidfVectorizer()
processado2 = vectorizer2.fit_transform(nomes)
print(nomes)
print(processado2.toarray())
vectorizer2.get_feature_names_out()

"""Na segunda representação, os acentos e caracteres especiais das stopwords são removidos para depois removermos as stopwords do texto, sem acentos e em letras minúsculas.

Tem representações são exemplificadas:
Contagem de unigramas de palavras, TFIDF de unigramas de palavras e contagem de trigramas de caracteres.
"""

from unicodedata import normalize

minhaStopList = [normalize('NFKD', n).encode('ASCII', 'ignore').decode('ASCII') for n in stopwords.words('portuguese')]
minhaStopList.append('ii')

vectorizer3 = CountVectorizer(strip_accents='ascii',
                      lowercase=True,
                      stop_words=minhaStopList)
processadoSemStop = vectorizer3.fit_transform(nomes)
print("\nRepresentacao por contagem de palavras:")
print(vectorizer3.get_feature_names_out())
print(processadoSemStop.toarray())


vectorizer3 = TfidfVectorizer(strip_accents='ascii',
                      lowercase=True,
                      stop_words=minhaStopList)
processadoSemStop = vectorizer3.fit_transform(nomes)
print("\nRepresentacao usando TF-IDF:")
print(vectorizer3.get_feature_names_out())
print(processadoSemStop.toarray())


vectorizer3 = CountVectorizer(strip_accents='ascii',
                      lowercase=True, ngram_range=(3,3), analyzer='char',
                      stop_words=minhaStopList)
processadoSemStop = vectorizer3.fit_transform(nomes)
print("\nRepresentacao por contagem de trigramas:")
print(vectorizer3.get_feature_names_out())
print(processadoSemStop.toarray())